[package]
name = "rust_implementation"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8"
csv = "1.1.6"
matrix_display = "0.3"
image = "0.23"
plotters = "0.3.3"
rayon = "1.8"
num-integer = "0.1"